# Generated by Django 5.0.6 on 2024-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('landing page', 'landing page'), ('blog', 'blog'), ('portfolio', 'portfolio'), ('business', 'business')], default='business', max_length=50)),
                ('url', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('profile_img', models.ImageField(upload_to='static/assets/img/portfolio/')),
            ],
        ),
    ]
