# Generated by Django 5.0.6 on 2024-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='detail_img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/portfolio/'),
        ),
        migrations.AddField(
            model_name='website',
            name='detail_img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/portfolio/'),
        ),
    ]
